services:
  web:
    build: ../distributor
    image: distributor-app:local
    restart: unless-stopped
    pull_policy: never
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../distributor:/app
      - ./license:/app/license/
      - ./processing:/app/processing
      - ./version:/app/version
      - ./backup:/app/backup
      - ./media:/app/media
      - static_volume:/app/staticfiles

    ports:
      - 8000:8000

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:8000/health/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

    command: python manage.py runserver 0.0.0.0:8000
  
  # web:
  #   image: ghcr.io/xitoss/distributor-app:latest  # from your GitHub package
  #   restart: unless-stopped
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./license:/app/license/
  #     - ./processing:/app/processing
  #     - ./media:/app/media
  #     - static_volume:/app/staticfiles
  #     - ./version:/app/version     
  #   expose:
  #     - "8000"
  # healthcheck:
  #     test: ["CMD-SHELL", "curl -fs http://localhost/health/ || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   command: python manage.py runserver 0.0.0.0:8000

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - ./media:/app/media
      - static_volume:/app/staticfiles
      - ./processing:/deployment/processing
      - ./nginx/maintenance:/var/www/maintenance
      - ./nginx/safety_pages:/var/www/safety
    
    depends_on:
      - web
  
  certbot:
    image: certbot/certbot
    # this will overriede chertbot from actual one and do nothing
    entrypoint: ["true"]

volumes:
  db_prod:
  static_volume:
