services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data
      - ./backup:/workspace/backup

  web:
    image: ghcr.io/xitoss/distributor-app:latest  # from your GitHub package
    pull_policy: always
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./license.pem:/app/license/license.pem
      - ./license_public.pem:/app/license/license_public.pem
      - ./processing:/app/processing
      - ./media:/app/media 
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    env_file: .env
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./media:/app/media
      - ./static:/app/staticfiles
      - ./nginx/certbot:/var/www/certbot
      - ./processing:/deployment/processing
      - ./nginx/maintenance:/var/www/maintenance
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./ssl:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    entrypoint: >
      sh -c "if [ ! -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then
              certbot certonly --webroot -w /var/www/certbot \
                -d ${DOMAIN} \
                --email ${LETSENCRYPT_EMAIL} \
                --agree-tos --non-interactive;
            fi;
            trap exit TERM; while :; do
              certbot renew --webroot -w /var/www/certbot --quiet;
              sleep 12h & wait $${!};
            done" 
  
  agent:
    build:
      context: ./sys_scripts
      dockerfile: Dockerfile.agent
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${AGENT_PORT:-6001}:${AGENT_PORT:-6001}"
    volumes:
      - .:/workspace
      - ./database:/workspace/database
      - ./backup:/workspace/backup
      - ./processing:/workspace/processing
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    