  # version: "3.8"
  services:
    db:
      image: postgres:15
      restart: unless-stopped
      environment:
        POSTGRES_DB: ${DB_NAME}
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
      volumes:
        - ./database:/var/lib/postgresql/data

    web:
      build: ../distributor   # builds from Dockerfile inside ../distributor
      image: distributor-app:local 
      restart: unless-stopped
      env_file:
        - .env
      depends_on:
        - db
      volumes:
        - ../distributor:/app 
        - ./media:/app/media
        - ./license.pem:/app/license/license.pem
        - ./license_public.pem:/app/license/license_public.pem
        # - ./staticfiles:/app/staticfiles 
      ports:
        - "8000:8000"
