FROM nginx:alpine
RUN apk add --no-cache gettext certbot


# Copy static nginx configs (loaded immediately, no processing)
COPY conf.d/global.conf /etc/nginx/conf.d/global.conf

# Copy templates, these templates include dynamic values, getting from start.sh
COPY conf.d/app.https.conf.template /etc/nginx/templates/

# Entry script
COPY start.sh /start.sh
RUN chmod +x /start.sh

# create directory for certbot
RUN mkdir -p /var/www/certbot

ENTRYPOINT ["/start.sh"]
