FROM nginx:alpine

# Install envsubst (part of gettext), used to substitute env vars in templates
RUN apk add --no-cache gettext

RUN rm -f /etc/nginx/conf.d/default.conf

COPY conf.d/app.dev.conf.template /etc/nginx/conf.d/default.conf