FROM nginx:alpine

# Install envsubst (part of gettext), used to substitute env vars in templates
RUN apk add --no-cache gettext

RUN rm -f /etc/nginx/conf.d/default.conf

COPY conf.d/app.dev.conf.template /etc/nginx/conf.d/default.conf

# create symbolic link for all nginx logs.
# reason: in general nginx writes logs, and the file might keep growing as people start using the application.
# my docker compose setup has limit set to 10mbx3 = 30 mb max size of logs.
# now as nginx logs will be  written inside docker itself, the size rotation will affect how big the log file grows.
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log