FROM nginx:alpine
RUN apk add --no-cache gettext

RUN rm -f /etc/nginx/conf.d/default.conf

# Copy templates
COPY conf.d/app.http.conf.template /etc/nginx/templates/
COPY conf.d/app.https.conf.template /etc/nginx/templates/

# Entry script
COPY start.sh /start.sh
RUN chmod +x /start.sh

ENTRYPOINT ["/start.sh"]
